<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-RGN3DGNM" failures="1" tests="3" name="Test" time="26.528" errors="0" timestamp="2025-05-31T15:47:35 IST">
  <testcase classname="electronics.TC_DWS_020_Test" name="clickOnElectronics" time="0.843"/>
  <testcase classname="computers.TC_DWS_010_Test" name="clickOnComputers" time="0.818"/>
  <testcase classname="books.TC_DWS_001_Test" name="clickOnBooks" time="1.094">
    <failure type="java.lang.AssertionError" message="expected [https://demowebshop.tricentis] but found [https://demowebshop.tricentis.com/books]">
      <![CDATA[java.lang.AssertionError: expected [https://demowebshop.tricentis] but found [https://demowebshop.tricentis.com/books]
at books.TC_DWS_001_Test.clickOnBooks(TC_DWS_001_Test.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- clickOnBooks -->
  <testcase classname="genericutility.BaseClass" name="@BeforeSuite reportConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite reportConfig -->
  <testcase classname="genericutility.BaseClass" name="@BeforeSuite reportConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite reportConfig -->
  <testcase classname="genericutility.BaseClass" name="@AfterSuite reportBackup" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite reportBackup -->
  <testcase classname="genericutility.BaseClass" name="@AfterSuite reportBackup" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite reportBackup -->
</testsuite> <!-- Test -->
